name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    # TODO: why do we need this action?
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Get package.json version
      id: package-version
      uses: martinbeentjes/npm-get-version-action@master
    - name: Login to DockerHub
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Install dev dependencies
      run: |
        npm i
    - name: Check coding style
      run: |
        npm run lint
    - name: Build Docker image
      env:
        PACKAGE_VERSION: ${{ steps.package-version.outputs.current-version}}
      run: |
        docker build ./ -t wesageio/demo-ems-ui:$PACKAGE_VERSION
    - name: Build Docker image to DockerHub repo
      env:
        PACKAGE_VERSION: ${{ steps.package-version.outputs.current-version}}
      run: |
        docker push wesageio/demo-ems-ui:$PACKAGE_VERSION
